### ISSUE TITLE
Device and Event Model Question

### ISSUE THREAD

**Issue by michaeltoohig** [mtnbarreto/flask-base-api#5]
I really like this project and have been using my variation of it as the base for my projects. Until now I never gave Device and Event models thought since I thought I had no use for them before and usually have just commented out those sections. But now I want to know what their intended use cases were and how to use them as you intended.

For the Device model it seems to be for sending messages to a device via an external service? But how do you collect this device information that is in the request headers? Is there an example of a frontend app that fingerprints a device or whatever and sends that with its request to register a device to a user? Or do I have this all wrong?

Then the Event model is used in your boilerplate is only seen in `manage.py` but then never referenced again so I'm not sure what the use case was. I can only assume I should define more app level `events` in the `api.common.utils.constants` and use those to register a history of events in the app such as "User did X", or "Scheduled Celery Task Completed" or something??? Could you elaborate a bit more on that as well? I was thinking of using something like [Flask-Bitmapist](https://pypi.org/project/Flask-Bitmapist/) for this use case until I remembered the `Event` model and perhaps if they have the same use cases I would just use the Event model you defined.

Again thanks for this boilerplate.

**Comment by mtnbarreto** [comment]
@michaeltoohig Sorry for the late response. I just updated the code to the latest dependencies versions. 

Event is a model to track notifications that users should be aware of. It can be a mobile notification or any chronological sequence of events relevant to the app you are building.  Initially, it was designed to send mobile push notifications through firebase services. 

Device information should be sent via the header during sign-in and sing up so each authenticated session has its corresponding device token (the identity needed to send push notification). I do not cover this because it is not part of flask REST API itself and requires some mobile development skills. 

The event model should be instantiated and saved in the Postgres db by the developer. It's intended to use relevant historical data to the end-user, like notion history, google drive files access changes, and so on. 

Feel free to delete these models if your particular app does not need these capabilities. There may be better approaches to solve the historical information saving them in a non-relational db.

**Comment by mtnbarreto** [comment]
I'm happy to help and clarify anything if you are still using the project.

**Comment by michaeltoohig** [comment]
Thanks for the reply, your project helped me years ago to start my own personal project. Its still in use. I'll look at upgrading it as you did but for now I have no time. Thank you.

**Comment by mtnbarreto** [comment]
Glad it helped you!
